openapi: 3.0.0

components:
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: An error has occurred
    Tea:
      type: object
      required: [id, name]
      properties:
        id:
          type: integer
          format: int32
        name:
          type: integer
          format: int32
        description: 
          $ref: "#/components/schemas/Description" 
    Description:
      type: string
      format: string
  examples:
    teaExample:
      id: 1
      title: "Barry's"
      description: "The finest tea humankind has ever known. A treat to the senses, a warm hug by the fire while a storm rages outside."