openapi: 3.0.0
info:
  version: 1.0.0
  title: tea

paths:
  /teas:
    get:
      operationId: getTeas
      summary: Returns all tea
      x-amazon-apigateway-integration:
        uri: ${API_LAMBDA_ARN}
        type: AWS_PROXY
        httpMethod: GET
      responses:
        "200":
          $ref: "#/components/responses/TeasResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "../tea/tea.yml#/components/schemas/Error"
    post:
      operationId: addTea
      summary: Add a new tea
      x-amazon-apigateway-integration:
        uri: ${API_LAMBDA_ARN}
        type: AWS_PROXY
        httpMethod: POST
      responses:
        "200":
          $ref: "#/components/responses/TeasResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "../tea/tea.yml#/components/schemas/Error"
  /tea/{teaId}:
    get:
      operationId: getTea
      summary: Returns a single tea
      x-amazon-apigateway-integration:
        uri: ${API_LAMBDA_ARN}
        type: AWS_PROXY
        httpMethod: GET
      parameters:
        - in: path
          name: teaId
          description: ID of the tea
          schema:
            type: integer
          required: true
      responses:
        "200":
          $ref: "#/components/responses/TeasResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "../tea/tea.yml#/components/schemas/Error"
components:
  responses:
    TeasResponse:
      description: List of Teas
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../tea/tea.yml#/components/schemas/Tea"
            example:
              - $ref: "../tea/tea.yml#/components/examples/teaExample"
    TeaResponse:
      description: Single Tea
      content:
        application/json:
          schema:
            $ref: "../tea/tea.yml#/components/schemas/Tea"
