openapi: 3.0.0
info:
  version: 1.0.0
  title: tea

paths:
  /teas:
    get:
      operationId: getTeas
      summary: Returns all tea
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:424795685451:function:TeaApiStack-TeaLambdaHandlerC1401C1C-SvKVPGwY4mYr/invocations"
        type: AWS_PROXY
        httpMethod: POST
      responses:
        "200":
          $ref: "#/components/responses/TeasResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "../tea/tea.yml#/components/schemas/Error"
    post:
      operationId: addTea
      summary: Add a new tea
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:424795685451:function:TeaApiStack-TeaLambdaHandlerC1401C1C-SvKVPGwY4mYr/invocations"
        type: AWS_PROXY
        httpMethod: POST
      responses:
        "200":
          $ref: "#/components/responses/TeasResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "../tea/tea.yml#/components/schemas/Error"
  /tea/{teaId}:
    get:
      operationId: getTea
      summary: Returns a single tea
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:424795685451:function:TeaApiStack-TeaLambdaHandlerC1401C1C-SvKVPGwY4mYr/invocations"
        type: AWS_PROXY
        httpMethod: GET
      parameters:
        - in: path
          name: teaId
          description: ID of the tea
          schema:
            type: integer
          required: true
      responses:
        "200":
          $ref: "#/components/responses/TeasResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "../tea/tea.yml#/components/schemas/Error"
components:
  responses:
    TeasResponse:
      description: List of Teas
      content:
        application/json:
          schema:
            type: object
            required: [teas]
            properties:
              teas:
                example:
                  - $ref: "../tea/tea.yml#/components/examples/teaExample"
                type: array
                items:
                  $ref: "../tea/tea.yml#/components/schemas/Tea"
    TeaResponse:
      description: Single Tea
      content:
        application/json:
          schema:
            $ref: "../tea/tea.yml#/components/schemas/Tea"
